disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - function_body_length
  - type_body_length
  - file_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - private_action
  - private_outlet
  - operator_usage_whitespace
  - nimble_operator
  - let_var_whitespace
  - closure_body_length

included:
  - App
  - Core
  - Features
  - LiveActivity
  - Managers
  - Models
  - Networking
  - Services
  - Utilities
  - Widgets

excluded:
  - Tests
  - Resources
  - .build
  - Build
